logging:
  num_ims_per_log: 500
  num_ims_per_save_image: 100000
  num_ims_per_checkpoint: 50000
max_imsize: 512
use_full_validation: False
load_fraction_of_dataset: False
dataset: galaxy
train_config:
  transition_iters: 600000
  learning_rate: 0.001
  amp_opt_level: O1
  batch_size_schedule:
    4: 128
    8: 128
    16: 128
    32: 64
    64: 32
    128: 16
    256: 4
    512: 4
    1024: 4

models:
  start_channel_size: 512
  latent_size: 512
  image_channels: 3
  generator:
    running_average_decay: 0.999
  discriminator:
    structure: normal

